server:
  port: 7001

eureka:
  instance:
    #eureka服务端实例名称
#    hostname: localhost
    hostname: eureka7001.com
  client:
    fetch-registry: false  #不注册自己
    register-with-eureka: false # 不检索自己
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/