server:
  port: 9527

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态生成路由的功能，用微服务名进行路由
      routes:
        - id: payment_routh #路由ID，无固定规则要求唯一，建议配合服务名
#          uri: http://localhost:8001
          uri: lb://payment-service
          predicates:
            - Path=/payment/get/**
        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://payment-service
          predicates:
            - Path=/payment/lb/**
#            - After=2099-07-27T08:05:14.510+08:00[Asia/Shanghai]

eureka:
  instance:
    hostname: gateway_service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka/
